"""Adds ParsedVersion to Appraisals table

Revision ID: 5240168a15e3
Revises: 47e13f1d69fc
Create Date: 2014-01-06 23:12:29.329925

"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(
                os.path.dirname(os.path.abspath(__file__))))))

# revision identifiers, used by Alembic.
revision = '5240168a15e3'
down_revision = '47e13f1d69fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Appraisals',
                  sa.Column('ParsedVersion', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Appraisals', 'ParsedVersion')
    ### end Alembic commands ###
