"""Adds index for Kind table

Revision ID: 7affe38061d
Revises: 5240168a15e3
Create Date: 2014-01-10 08:16:17.912860

"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(
                os.path.dirname(os.path.abspath(__file__))))))

# revision identifiers, used by Alembic.
revision = '7affe38061d'
down_revision = '5240168a15e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Appraisals_Kind', 'Appraisals', ['Kind'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Appraisals_Kind', 'Appraisals')
    ### end Alembic commands ###
